### PR TITLE
Do not fill in LogRecord caller data by default in slf4j wrapper

### LINKED ISSUE #3112: [performance] JDK14LoggerAdapter class creates many exceptions
this is a record place for the number of exceptions:  
image

### PR DESCRIPTION
**Pull request by Janmm14**
I am no expert with slf4j/java1.4 logging framework, but as bungeecord by default does not use the caller data, it should be safe to not fill it in by default.
Added system property `net.md_5.bungee.slf4j-caller-data` to restore current behaviour in case custom logging requires caller data.

Should slightly improve performance of bungeecord.

Closes #3112

### CODE REVIEW

**Comment by md-5** [comment]
But Bungeecord doesn't even use slf4j by itself, only plugins can log things to it in the first place

**Comment by Janmm14** [comment]
I meant that eventual plugins or libs using slf4j logging which we bridge to java Loggers dont fill LogRecords with data which is not needed by bungee's loggers in the end.

File: slf4j/src/main/java/org/slf4j/impl/JDK14LoggerAdapter.java [hunk 1]
```diff
@@ -585,13 +585,18 @@ private void log(String callerFQCN, Level level, String msg, Throwable t) {
     static String SELF = JDK14LoggerAdapter.class.getName();
     static String SUPER = MarkerIgnoringBase.class.getName();
 
+    private static final boolean fillCallerData = System.getProperty( "net.md_5.bungee.slf4j-caller-data" ) != null;
```
Comment (md-5) [inline slf4j/src/main/java/org/slf4j/impl/JDK14LoggerAdapter.java:588]: FILL_CALLER_DATA, Boolean.getBoolean

Comment (Janmm14) [reply slf4j/src/main/java/org/slf4j/impl/JDK14LoggerAdapter.java]: Took some time but done

**Comment by Janmm14** [comment]
@md-5 So this self-assign means that you are going to change some stuff and then handle this?
